version: '2'
services:
  backendDB:
    image: mongo
    ports:
      - '27017:27017'
    networks: 
      - myNet
  frontEnd:
    build:
      context: ./originalSrc
    image: my-golang-app3
    ports:
      - '8000:8000'
    networks:
      - myNet
    environment: 
      - MONGODB_CONNECTION_STRING=mongodb://backendDB:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false

networks:
  myNet: